In [8]:
import numpy as np
from sklearn import preprocessing

In [2]:
sample_data=np.array([[2.1,-1.9,5.5],
                      [-2.3,2.4,3.5],
                      [3.4,5.3,3.4]])
sample_data

array([[ 2.1, -1.9,  5.5],
       [-2.3,  2.4,  3.5],
       [ 3.4,  5.3,  3.4]])

In [3]:
sample_data.shape

(3, 3)

In [4]:
#Binarisation
preprocessor=preprocessing.Binarizer(threshold=0.5)
binarised_data=preprocessor.transform(sample_data)

binarised_data

array([[1., 0., 1.],
       [0., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#Scaling
preprocessor=preprocessing.Binarizer(threshold=0.5)
binarised_data=preprocessor.transform(sample_data)

binarised_data

In [6]:
preprocessor=preprocessing.MinMaxScaler(feature_range=(0,1))
preprocessor.fit(sample_data)
scaled_data=preprocessor.transform(sample_data)

scaled_data

array([[0.77192982, 0.        , 1.        ],
       [0.        , 0.59722222, 0.04761905],
       [1.        , 1.        , 0.        ]])

In [10]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-2.3,  2.4,  3.5],
       [ 3.4,  5.3,  3.4]])

In [9]:
#L1 Normalisation : Least Absolute Deviations

l1_normalised_data=preprocessing.normalize(sample_data,norm='l1')
l1_normalised_data

array([[ 0.22105263, -0.2       ,  0.57894737],
       [-0.2804878 ,  0.29268293,  0.42682927],
       [ 0.28099174,  0.43801653,  0.28099174]])

In [11]:
#L2 Normalisation : Least Square

l2_normalised_data=preprocessing.normalize(sample_data,norm='l2')
l2_normalised_data

array([[ 0.33946114, -0.30713151,  0.88906489],
       [-0.4764857 ,  0.49720247,  0.72508694],
       [ 0.47511805,  0.74062519,  0.47511805]])